from enum import Enum


class DeviceType(str, Enum):
    WAVE = "WAVE"
    WAVE_MIST = "WAVE_MIST"
    WAVE_GEN2 = "WAVE_GEN2"
    WAVE_MINI = "WAVE_MINI"
    WAVE_PLUS = "WAVE_PLUS"
    WAVE_CO2 = "WAVE_CO2"
    VIEW_PLUS = "VIEW_PLUS"
    VIEW_PLUS_BUSINESS = "VIEW_PLUS_BUSINESS"
    VIEW_POLLUTION = "VIEW_POLLUTION"
    VIEW_RADON = "VIEW_RADON"
    VIEW_CO2 = "VIEW_CO2"
    SPACE_CO2_MINI = "SPACE_CO2_MINI"
    WAVE_ENHANCE = "WAVE_ENHANCE"
    HUB = "HUB"
    HOME = "HOME"
    PRO = "PRO"
    CLOUDBERRY = "CLOUDBERRY"
    AIRTIGHT = "AIRTIGHT"
    AGGREGATED_GROUP = "AGGREGATED_GROUP"
    ZONE_GROUP = "ZONE_GROUP"
    BALANCE_CONTROL = "BALANCE_CONTROL"
    INLET_AIR_CONTROL = "INLET_AIR_CONTROL"
    VENT_CONTROLLER = "VENT_CONTROLLER"
    AIRLY = "AIRLY"
    AIRLY_NO2 = "AIRLY_NO2"
    AIRLY_CO = "AIRLY_CO"
    AIRLY_NO = "AIRLY_NO"
    BREEZOMETER_WEATHER = "BREEZOMETER_WEATHER"
    BACNET = "BACNET"
    UNKNOWN = "UNKNOWN"

    def __str__(self) -> str:
        return str(self.value)
