name: Build Status
on:
  push:
    branches:
      - master
    paths:
      - 'wave_reader/**'
      - 'tests/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Dependencies
      run: |
        sudo apt-get install libglib2.0-dev bluez -y
        python -m pip install --upgrade pip
        pip install tox coveralls
    - name: Run Tests
      run: |
        tox
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        verbose: true
